fruits = []
f1 = input("enter name of fruit: ")
fruits.append(f1)
f2 = input("enter name of fruit: ")
fruits.append(f2)
f3 = input("enter name of fruit: ")
fruits.append(f3)
f4 = input("enter name of fruit: ")
fruits.append(f4)
f5 = input("enter name of fruit: ")
fruits.append(f5)
print(fruits)