marks = []
f1 = input("enter marks : ")
marks.append(f1)
f2 = input("enter marks: ")
marks.append(f2)
f3 = input("enter marks: ")
marks.append(f3)
f4 = input("enter marks: ")
marks.append(f4)
f5 = input("enter marks: ")
marks.append(f5)
print(marks)
marks.sort()